# Folder paths
PROCS: procs

# Logging
LOG_LEVEL: INFO     # Possible level options are INFO, IVERILOG, WARN, and ERROR
LOG_LOC: FILE       # Possible location options are TERM and FILE
LOG_DIR: log
LOG_ROLL: True 


# Other 
OS: MACM1       # Possible os options are MACM1, MACINTEL, WIN, and LINUX
OUT_ROLL: True